spring.application.name=spring1
spring.datasource.url=jdbc:mysql://localhost:3306/db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.expiration=300000
jwt.secret=secretcode5456y6ggtf5drgghfhbyg74338ufhdyubdf
